# docker-compose.monitoring.yml
version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: tomyongji-grafana-prod
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: tomyongji-prometheus-prod
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - app_network

  loki:
    image: grafana/loki:2.9.0
    container_name: tomyongji-loki-prod
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - app_network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: tomyongji-promtail-prod
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log/tomyongji:/var/log/tomyongji
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - loki

volumes:
  grafana-data:
  prometheus-data:
  loki-data:

networks:
  app_network:
    external: true