version: '2.4'

services:
  app:
    image: eeeseohyun/tomyongji:latest
    container_name: tomyongji-app-prod
    ports:
      - "8080:8080"
    volumes:
      - /var/log/tomyongji:/var/log/tomyongji
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    networks:
        - app_network

  nginx:
    image: eeeseohyun/tomyongji-nginx:latest
    container_name: tomyongji-nginx-prod
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for SSL certificate...';
        while ! test -f /etc/letsencrypt/live/api.tomyongji.com/fullchain.pem; do
          sleep 5;
        done;
        echo 'Certificate found! Starting Nginx...';
        nginx -g 'daemon off;'
      "
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: tomyongji-certbot-prod
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    restart: unless-stopped
    networks:
      - app_network

  # --- 모니터링 스택 ---
  grafana:
    image: grafana/grafana:latest
    container_name: tomyongji-grafana-prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - app_network

  loki:
    image: grafana/loki:latest
    container_name: tomyongji-loki-prod
    ports:
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - app_network

  promtail:
    image: grafana/promtail:latest
    container_name: tomyongji-promtail-prod
    ports:
      - "9080:9080"
    restart: unless-stopped
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log/tomyongji:/var/log/tomyongji
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: tomyongji-prometheus-prod
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  grafana-data:
  loki-data:
  prometheus-data: