
services:
  app:
    image: eeeseohyun/tomyongji
    environment:
      - PORT=8080
    container_name: tomyongji_app
    ports:
      - "8080:8080"  # 컨테이너의 8080 포트를 호스트의 8080 포트와 연결
    networks:
      - app_network  # 여기서 'app_network'로 변경

  nginx:
    image: nginx:latest
    container_name: tomyongji-nginx
    ports:
      - "80:80"     # HTTP 포트
      - "443:443"   # HTTPS 포트
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app_network  # 여기서 'app_network'로 변경

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - ./loki/data:/loki
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

networks:
  app_network:  # 사용자 정의 네트워크 정의
    driver: bridge
