version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - spring

  spring:
    image: jinhyoung9380/tomyongji:latest
    expose:
      - "8080"
    volumes:
      - ./application.properties:/app/config/application.properties
    command: [ "java", "-jar", "/app.jar", "--spring.config.location=file:/app/config/application.properties" ]

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
