version: '3.8'

services:
  app:
    image: eeeseohyun/tomyongji
    environment:
      - PORT=8080
    container_name: tomyongji_app
    ports:
      - "8080:8080"  # 컨테이너의 8080 포트를 호스트의 8080 포트와 연결
    networks:
      - app_app_network  # 여기서 'app_network'로 변경

  nginx:
    image: nginx:latest
    container_name: tomyongji-nginx
    ports:
      - "80:80"     # HTTP 포트
      - "443:443"   # HTTPS 포트
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app_app_network  # 여기서 'app_network'로 변경

networks:
  app_app_network:  # 사용자 정의 네트워크 정의
    driver: bridge
