name: tomyongji-dev
version: '2.4'

services:
  spring:
    image: jinhyoung9380/tomyongji:latest
    ports:
      - "8080:8080"

    # ⬇⬇ 임시 우회: Actuator CPU 메트릭 바인더 OFF
    environment:
      - MANAGEMENT_METRICS_BINDERS_PROCESSOR_ENABLED=false

    # 부팅 지연 대비 헬스체크 여유 확대 + curl 없을 때 wget로 대체
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health || wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s

    restart: unless-stopped

  nginx:
    image: nginx:latest
    depends_on:
      spring:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    restart: unless-stopped

