auth_enabled: false

server:
  http_listen_port: 3100
  
limits_config:
  # 최대 entry size 설정 (2 MB)
  max_entry_size_bytes: 2097152
  
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules

  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-12
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  storage:
    type: local
    
    local:
      directory: /tmp/loki/rules


