auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 15m
  chunk_retain_period: 1h
  max_chunk_age: 1h
  max_chunk_size: 10485760 # 최대 청크 크기 (기본값 10MB)

storage_config:
  tsdb:
    active_index_directory: /loki/index  # tsdb 인덱스를 위한 디렉토리
    cache_location: /loki/cache         # 캐시 위치 설정
    retention_deletes_enabled: true     # 만료된 데이터 삭제 활성화
    retention_period: 168h             # 7일 데이터 유지 (예시)
  filesystem:
    directory: /loki/chunks  # 파일 시스템을 사용하여 청크 저장

limits_config:
  max_streams_per_user: 10000
  allow_structured_metadata: false  # Structured Metadata 비활성화

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb  # tsdb 인덱스를 사용
      object_store: filesystem
      schema: v13  # schema v13 사용
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor  # 컴팩터 작업 디렉토리 설정
  path_prefix: /loki                 # 기본 경로 설정
