auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki  # 기본 디렉토리 설정

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2023-12-01
      store: boltdb-shipper  # 볼트 DB 사용
      object_store: filesystem
      schema: v11  # 스키마 버전
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  max_global_streams_per_user: 10000
  allow_structured_metadata: false  # Structured Metadata 비활성화

compactor:
  working_directory: /loki/compactor  # Compactor 작업 디렉토리
