server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml

clients:
  # push할 Loki의 주소
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-logs
    static_configs:
      - targets:
          - localhost
        labels:
          # 수집되는 로그에 추가될 메타데이터(레이블)를 정의합니다.
          # 예시 : job=varlogs
          job: varlogs
          __path__: "var/log/tomyongji/*.log"

    pipeline_stages:
      # 여러 줄에 걸친 로그 항목을 하나로 묶는 역할을 합니다.
      - multiline:
          firstline: '^\<.*'  # 로그의 시작을 나타내는 정규식 (예: <2025-03-19)
          separator: '\n<.*'  # 로그의 구분자 (각각의 새로운 로그 항목은 <로 시작)
  ~