server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: dev-spring-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dev_log
          __path__: /var/log/tomyongji-dev/*.log

    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'  # ex) 2025-05-28