version: '2.4'

services:
  spring:
    # Docker Hub에서 받아올 이미지 정보만 남깁니다.
    image: jinhyoung9380/tomyongji:dev
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health || wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    restart: unless-stopped

  nginx:
    # Docker Hub에서 받아올 이미지 정보만 남깁니다.
    image: jinhyoung9380/tomyongji-nginx:dev # dev 환경용 nginx 이미지 이름
    depends_on:
      spring:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    restart: unless-stopped