# HTTP → HTTPS Redirect
server {
    listen 80;
    server_name tomyongji-dev.site api.tomyongji-dev.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS Settings
server {
    listen 443 ssl;
    server_name tomyongji-dev.site api.tomyongji-dev.site;

    ssl_certificate /etc/letsencrypt/live/tomyongji-dev.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tomyongji-dev.site/privkey.pem;

    location / {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}