apiVersion: 1

policies:
  - orgId: 1
    receiver: email-alert
    group_by: [ "category" ]
    routes:
      - receiver: email-alert
        object_matchers:
          - [ "severity", "=", "critical" ]
        group_wait: 10s
        repeat_interval: 15m
      - receiver: email-alert
        object_matchers:
          - [ "severity", "=", "warning" ]
        group_wait: 30s
        repeat_interval: 1h
